# Generated by Django 3.0.5 on 2023-07-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('lote', models.TextField()),
                ('presentacion', models.TextField()),
                ('codBarras', models.TextField()),
                ('laboratorio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPaciente', models.TextField()),
                ('Nombre', models.TextField()),
                ('apellidoP', models.TextField()),
                ('apellidoM', models.TextField()),
                ('sexo', models.TextField()),
                ('direccion', models.TextField()),
            ],
        ),
    ]
