# Generated by Django 3.0.5 on 2023-07-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miFarma', '0002_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
