# Generated by Django 3.0.5 on 2023-07-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miFarma', '0003_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField()),
                ('contraseña', models.TextField()),
                ('rol', models.TextField()),
            ],
        ),
    ]
